AVAILABLE_CASH = 1000
RISK_PER_TRADE = 1.0
MIN_SCORE = 70
TOP_RESULTS = 20

REPORT_FOLDER = "reports"
CHART_FOLDER = "charts"

MARKET_INDEX = "SPY"

MIN_PRICE = 5.0
MIN_AVERAGE_DOLLAR_VOLUME = 5_000_000
AVERAGE_VOLUME_DAYS = 20
