"""Normalize published report presentation without changing dates in data or URLs."""
from datetime import datetime, timezone, timedelta
from pathlib import Path
import re
from zoneinfo import ZoneInfo

NEW_YORK = ZoneInfo('America/New_York')
FILTER_MODULE = '<script type="module" src="/StockScanner/table-filters.js"></script>'

CHART_LABELS = "chartData.labels.map((value) => { const [year, month, day] = value.split('-'); return day + '/' + ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][Number(month) - 1] + '/' + year; })"
SNAPSHOT_READ = '        const snapshot = await response.json();'
SNAPSHOT_CLOCK = """
        const { formatDateTime } = await import('/StockScanner/date-format.js');
        snapshot.generated_at_new_york = snapshot.generated_at ? formatDateTime(snapshot.generated_at) : null;
        snapshot.price_timestamp_new_york = snapshot.price_timestamp ? formatDateTime(snapshot.price_timestamp) : null;"""
DISPLAY_TIMESTAMP = re.compile(
    r'\b(?P<date>\d{2}/[A-Z][a-z]{2}/\d{4}|\d{4}-\d{2}-\d{2})'
    r',? (?P<clock>\d{1,2}:\d{2}(?::\d{2})?)(?: (?P<period>AM|PM))?'
    r'(?: (?P<zone>EDT|EST|UTC|GMT))?\b'
)


def _format_timestamp(match):
    date_format = '%Y-%m-%d' if '-' in match['date'] else '%d/%b/%Y'
    clock_format = '%I:%M' if match['period'] else '%H:%M'
    if match['clock'].count(':') == 2:
        clock_format += ':%S'
    value = f"{match['date']} {match['clock']}"
    if match['period']:
        value += f" {match['period']}"
        clock_format += ' %p'
    try:
        moment = datetime.strptime(value, f'{date_format} {clock_format}')
    except ValueError:
        return match[0]
    # Legacy reports without a zone were generated by the UTC CI runner.
    zone = {'EDT': timezone(timedelta(hours=-4)), 'EST': timezone(timedelta(hours=-5))}.get(match['zone'], timezone.utc)
    return moment.replace(tzinfo=zone).astimezone(NEW_YORK).strftime('%d/%b/%Y, %H:%M %Z')


def _format_visible_times(source):
    # Only text nodes, never ISO data, URLs, attributes, or JavaScript literals.
    parts = re.split(r'(<script\b[^>]*>[\s\S]*?</script\s*>|<style\b[^>]*>[\s\S]*?</style\s*>|<!--.*?-->|<[^>]+>)', source, flags=re.I | re.S)
    for i in range(0, len(parts), 2):
        parts[i] = DISPLAY_TIMESTAMP.sub(_format_timestamp, parts[i])
    return ''.join(parts)


def format_report(source):
    if ('id="filterInput"' in source or 'id="kpiStockSearch"' in source) and FILTER_MODULE not in source:
        source = source.replace('</body>', FILTER_MODULE + '\n</body>')
    source = source.replace('https://github.com/aksamuel/StockScanner#readme', '/StockScanner/help.html')
    source = source.replace('labels: chartData.labels,', 'labels: ' + CHART_LABELS + ',')
    if 'snapshot.generated_at_new_york' in source and SNAPSHOT_CLOCK.strip() not in source:
        source = source.replace(SNAPSHOT_READ, SNAPSHOT_READ + SNAPSHOT_CLOCK)
    source = re.sub(r'\b(\d{2}) (January|February|March|April|May|June|July|August|September|October|November|December) (\d{4})\b', lambda m: f'{m[1]}/{m[2][:3]}/{m[3]}', source)
    source = re.sub(r'(?<=>)(\d{4}-\d{2}-\d{2})(?=<)', lambda m: datetime.strptime(m[1], '%Y-%m-%d').strftime('%d/%b/%Y'), source)
    source = re.sub(r'(Reports for |Generated at: |Generated: |Generated on )(\d{4}-\d{2}-\d{2})', lambda m: m[1] + datetime.strptime(m[2], '%Y-%m-%d').strftime('%d/%b/%Y'), source)
    return _format_visible_times(source)


def main():
    root = Path(__file__).resolve().parents[1]
    for path in [*(root / 'reports').rglob('*.html'), *(root / name for name in ['index.html', 'technical.html', 'analysts.html', 'bought-selection.html'])]:
        if not path.is_file():
            continue
        source = path.read_text(encoding='utf-8')
        formatted = format_report(source)
        if formatted != source:
            path.write_text(formatted, encoding='utf-8')


if __name__ == '__main__':
    main()
