alter table public.price_snapshots
  add column if not exists price_timestamps jsonb not null default '{}'::jsonb;

alter table public.price_snapshots
  drop constraint if exists price_snapshots_price_timestamps_object_check,
  add constraint price_snapshots_price_timestamps_object_check
    check (jsonb_typeof(price_timestamps) = 'object');

comment on column public.price_snapshots.price_timestamps is
  'Most recent quote timestamp by symbol, retained when a provider refresh fails.';

create table if not exists public.failed_symbol_scans (
  id bigint generated by default as identity primary key,
  market_date date not null,
  scan_type text not null check (scan_type in ('daily', 'hourly')),
  workflow_run_id bigint not null,
  scan_at timestamptz not null default now(),
  attempted_symbols jsonb not null default '[]'::jsonb
    check (jsonb_typeof(attempted_symbols) = 'array'),
  failed_symbols jsonb not null default '[]'::jsonb
    check (jsonb_typeof(failed_symbols) = 'array'),
  created_at timestamptz not null default now(),
  constraint failed_symbol_scans_run_unique unique (scan_type, workflow_run_id)
);

create index if not exists failed_symbol_scans_date_scan_at_idx
  on public.failed_symbol_scans (market_date desc, scan_at desc);

alter table public.failed_symbol_scans enable row level security;
revoke all on table public.failed_symbol_scans from public, anon, authenticated;
grant select on table public.failed_symbol_scans to authenticated;
grant select, insert, update on table public.failed_symbol_scans to service_role;
grant usage, select on sequence public.failed_symbol_scans_id_seq to service_role;

create policy "StockScanner admin can read failed-symbol scan history"
  on public.failed_symbol_scans
  for select
  to authenticated
  using (
    lower(coalesce((select auth.jwt()) ->> 'email', '')) = 'aaksamuel@zohomail.com'
  );

comment on table public.failed_symbol_scans is
  'Immutable per-run history of symbols that could not be refreshed or scanned, grouped by New York market date.';

create table if not exists public.failed_symbol_queue (
  scan_type text not null check (scan_type in ('daily', 'hourly')),
  symbol text not null,
  status text not null check (status in ('pending', 'resolved')),
  first_failed_at timestamptz not null,
  last_failed_at timestamptz not null,
  last_failed_market_date date not null,
  last_workflow_run_id bigint not null,
  last_reason text not null default '',
  resolved_at timestamptz,
  primary key (scan_type, symbol)
);

create index if not exists failed_symbol_queue_pending_idx
  on public.failed_symbol_queue (scan_type, last_failed_market_date)
  where status = 'pending';

alter table public.failed_symbol_queue enable row level security;
revoke all on table public.failed_symbol_queue from public, anon, authenticated;
grant select, insert, update on table public.failed_symbol_queue to service_role;

create or replace function public.record_failed_symbol_scan(
  p_market_date date,
  p_scan_type text,
  p_workflow_run_id bigint,
  p_scan_at timestamptz,
  p_attempted_symbols jsonb,
  p_failed_symbols jsonb
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if p_scan_type not in ('daily', 'hourly')
     or jsonb_typeof(p_attempted_symbols) <> 'array'
     or jsonb_typeof(p_failed_symbols) <> 'array' then
    raise exception 'Invalid failed-symbol scan payload';
  end if;

  insert into public.failed_symbol_scans (
    market_date, scan_type, workflow_run_id, scan_at,
    attempted_symbols, failed_symbols
  ) values (
    p_market_date, p_scan_type, p_workflow_run_id, p_scan_at,
    p_attempted_symbols, p_failed_symbols
  )
  on conflict (scan_type, workflow_run_id) do update
    set scan_at = excluded.scan_at,
        attempted_symbols = excluded.attempted_symbols,
        failed_symbols = excluded.failed_symbols;

  insert into public.failed_symbol_queue (
    scan_type, symbol, status, first_failed_at, last_failed_at,
    last_failed_market_date, last_workflow_run_id, last_reason, resolved_at
  )
  select
    p_scan_type,
    upper(trim(failure->>'symbol')),
    'pending',
    p_scan_at,
    p_scan_at,
    p_market_date,
    p_workflow_run_id,
    coalesce(failure->>'reason', ''),
    null
  from jsonb_array_elements(p_failed_symbols) as failure
  where nullif(trim(failure->>'symbol'), '') is not null
  on conflict (scan_type, symbol) do update
    set status = 'pending',
        last_failed_at = excluded.last_failed_at,
        last_failed_market_date = excluded.last_failed_market_date,
        last_workflow_run_id = excluded.last_workflow_run_id,
        last_reason = excluded.last_reason,
        resolved_at = null;

  update public.failed_symbol_queue as queued
  set status = 'resolved',
      resolved_at = p_scan_at
  where queued.scan_type = p_scan_type
    and queued.status = 'pending'
    and queued.symbol in (
      select upper(trim(attempted.value #>> '{}'))
      from jsonb_array_elements(p_attempted_symbols) as attempted(value)
    )
    and not exists (
      select 1
      from jsonb_array_elements(p_failed_symbols) as failure
      where upper(trim(failure->>'symbol')) = queued.symbol
    );

  return true;
end;
$$;

revoke all on function public.record_failed_symbol_scan(date, text, bigint, timestamptz, jsonb, jsonb)
  from public, anon, authenticated;
grant execute on function public.record_failed_symbol_scan(date, text, bigint, timestamptz, jsonb, jsonb)
  to service_role;
